### ISSUE TITLE
Check if sonos.smartgic.io is up and running

### ISSUE THREAD

**Issue by goldyfruit** [smartgic/mycroft-sonos-controller-skill#12]
If https://sonos.smartgic.io is not up and running then the skill returns this error during authentication.
```
<?xml version="1.0" ?>
<credentials xmlns="http://www.sonos.com/Services/1.1">
  <deviceId>5C-AA-FD-0D-5F-EC:2</deviceId>
  <deviceProvider>Sonos</deviceProvider>
  <context>
    <timezone>+01:00</timezone>
  </context>
  <loginToken>
    <householdId>Sonos_OBZspei5E7mCDd1JYw7D9RO6fA</householdId>
  </loginToken>
</credentials>

b'<?xml version=\'1.0\' encoding=\'UTF-8\'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><getAppLinkResponse xmlns="http://www.sonos.com/Services/1.1"><getAppLinkResult><authorizeAccount><appUrlStringId>SIGN_IN</appUrlStringId><deviceLink><regUrl>https://spotify-v5.ws.sonos.com/deviceLink/home?linkCode=DITBJ1</regUrl><linkCode>DITBJ1</linkCode><showLinkCode>false</showLinkCode></deviceLink></authorizeAccount><createAccount><appUrlStringId>CREATE_NEW</appUrlStringId></createAccount></getAppLinkResult></getAppLinkResponse></soapenv:Body></soapenv:Envelope>'
2021-08-10 21:24:44.202 | ERROR    |     1 | concurrent.futures | exception calling callback for <Future at 0x7f6c0e8080 state=finished raised JSONDecodeError>
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/pyee/_executor.py", line 56, in _callback
    self.emit('error', exc)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mycroft/core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 364, in handle_settings_change
    self.settings_change_callback()
  File "/opt/mycroft/skills/mycroft-sonos-controller-skill.smartgic/__init__.py", line 313, in on_settings_changed
    authentication(self)
  File "/opt/mycroft/skills/mycroft-sonos-controller-skill.smartgic/utils.py", line 60, in authentication
    url_shorted = req.json()['link']
  File "/opt/mycroft-venv/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The code should handle this error and detect if https://sonos.smartgic.io is available.

**Comment by goldyfruit** [comment]
https://github.com/smartgic/mycroft-sonos-controller-skill/commit/9cdeb8aaf01d67eb27e8fa1639eabfc590fca906
