### ISSUE TITLE
Handle error when speaker is not found

### ISSUE THREAD

**Issue by goldyfruit** [smartgic/mycroft-sonos-controller-skill#17]
```
2021-11-05 16:36:54,333 WARNING SonosController us speaker not found
2021-11-05 16:36:54,659 ERROR mycroft.skills.mycroft_skill.mycroft_skill:on_error:923 An error occurred while processing a request in Sonos Controller
Traceback (most recent call last):
  File "/home/mycroft/core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-sonos-controller-skill.smartgic/__init__.py", line 232, in _handle_volume_down
    extras=DEFAULT_VOL_INCREMENT)
  File "/opt/mycroft/skills/mycroft-sonos-controller-skill.smartgic/utils.py", line 261, in run_command
    if get_state(self, device.player_name) == state.upper():
AttributeError: 'NoneType' object has no attribute 'player_name'
```

**Comment by goldyfruit** [comment]
Fixed 54ea592681c327b7261781bf893bd3f1d26b3225
