### ISSUE TITLE
OSError: [Errno 113] No route to host 

### ISSUE THREAD

**Issue by goldyfruit** [smartgic/mycroft-sonos-controller-skill#18]
If for some reason a speaker if not reachable on the network, the error should be handle properly to avoid this error.
```
2021-11-07 13:37:06,149 ERROR mycroft.skills.mycroft_skill.mycroft_skill:on_error:923 An error occurred while processing a request in Sonos Controller
Traceback (most recent call last):
  File "/opt/mycroft-venv/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/mycroft-venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/opt/mycroft-venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:
```

**Comment by goldyfruit** [comment]
```
Traceback (most recent call last):
  File "/home/mycroft/core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-sonos-controller-skill.smartgic/__init__.py", line 221, in _handle_volume_up
    extras=DEFAULT_VOL_INCREMENT)
  File "/opt/mycroft/skills/mycroft-sonos-controller-skill.smartgic/utils.py", line 275, in run_command
    if get_state(self, device.player_name) == state.upper():
  File "/opt/mycroft/skills/mycroft-sonos-controller-skill.smartgic/utils.py", line 123, in get_state
    return device.get_current_transport_info()[key]
  File "/opt/mycroft-venv/lib/python3.7/site-packages/soco/core.py", line 1451, in get_current_transport_info
    ("InstanceID", 0),
  File "/opt/mycroft-venv/lib/python3.7/site-packages/soco/services.py", line 209, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/soco/services.py", line 482, in send_command
    self.base_url + self.control_url, headers=headers, data=body.encode("utf-8")
  File "/opt/mycroft-venv/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/mycroft-venv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.112', port=1400): Max retries exceeded with url: /MediaRenderer/AVTransport/Control (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b0ca2b0>: Failed to establish a new connection: [Errno 113] No route to host'))
```
