### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'player_name'

### ISSUE THREAD

**Issue by goldyfruit** [smartgic/mycroft-sonos-controller-skill#27]
```
2021-11-24 02:42:14,632 DEBUG mycroft.skills.intent_service:_normalize_all_utterances:72 Utterances: [("what's playing on the face", 'what is playing on the face')]
2021-11-24 02:42:14,634 DEBUG urllib3.connectionpool http://192.168.1.222:1400 "POST /MediaRenderer/AVTransport/Control HTTP/1.1" 200 399
2021-11-24 02:42:14,662 DEBUG mycroft.skills.intent_services.padatious_service:_match_level:47 Padatious Matching confidence > 0.95
2021-11-24 02:42:14,719 WARNING SonosController the face speaker not found
2021-11-24 02:42:15,065 ERROR mycroft.skills.mycroft_skill.mycroft_skill:on_error:923 An error occurred while processing a request in Sonos Controller
Traceback (most recent call last):
  File "/home/mycroft/core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-sonos-controller-skill.smartgic/__init__.py", line 309, in _handle_what_is_playing
    get_track_info(self, message.data.get('speaker'), False)
  File "/opt/mycroft/skills/mycroft-sonos-controller-skill.smartgic/utils.py", line 341, in get_track_info
    if get_state(self, device.player_name) == 'PLAYING':
AttributeError: 'NoneType' object has no attribute 'player_name'
```

**Comment by goldyfruit** [comment]
Should have been fixed in #17 but it's not.
