### ISSUE TITLE
"play jazz playlist from tidal on office" returns an error

### ISSUE THREAD

**Issue by goldyfruit** [smartgic/mycroft-sonos-controller-skill#40]
```
2022-02-08 15:40:17.625 | ERROR    |     1 | SonosController | Unknown music service: 'Tidal'
2022-02-08 15:40:17.625 | WARNING  |     1 | SonosController | playlists category not found for Tidal service
2022-02-08 15:40:17.646 | ERROR    |     1 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:923 | An error occurred while processing a request in Sonos Controller
Traceback (most recent call last):
  File "/home/mycroft/core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-sonos-controller-skill.smartgic/__init__.py", line 132, in _handle_playlist
    search(self, service, speaker, 'playlists', playlist=playlist)
  File "/opt/mycroft/skills/mycroft-sonos-controller-skill.smartgic/search.py", line 56, in search
    'category': category})
  File "/home/mycroft/core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1227, in speak_dialog
    self.dialog_renderer.render(key, data),
  File "/home/mycroft/core/mycroft/dialog/dialog.py", line 110, in render
    line = line.format(**context)
KeyError: 'service'
```

**Comment by goldyfruit** [comment]
Fixed via https://github.com/smartgic/mycroft-sonos-controller-skill/commit/321dd328f69b0827f145d565a8037e8baae16014
