### ISSUE TITLE
Request to play music results in errors

### ISSUE THREAD

**Issue by MaartenW** [smartgic/mycroft-sonos-controller-skill#43]
Found speakers, got info on 'm, set default music service (Apple) but can't seem to play any music.
Get the following:
```
~~~~es.music_service | Unhandled SOAP Fault. Code: SOAP-ENV:Server. Detail: <Element 'detail' at 0x43de36c0>. String: There was an error processing your request
Traceback (most recent call last):
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/soco/music_services/music_service.py", line 189, in call
    result_elt = message.call()
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/soco/soap.py", line 324, in call
    raise SoapFault(faultcode, faultstring, faultdetail)
soco.soap.SoapFault: SOAP-ENV:Server: There was an error processing your request
 21:01:35.980 | ERROR    |   667 | SonosController | ('There was an error processing your request', 'SOAP-ENV:Server')
```

Any ideas?

**Comment by goldyfruit** [comment]
Hey @MaartenW 

I should not have merged the Apple Music music service. It is not working I would like yet.

For Apple Music support with Sonos, I would recommend to check this [skill]( https://github.com/QW3RTZUI0P/sonos-music-controller-skill) until I merge the full working code
